### ISSUE TITLE
[BUG] Javascript exception when click on the "Translate" button

### ISSUE THREAD

**Issue by p4535992** [Meneltamar/fvtt-comprehend-languages#6]
**Module Version:** v1.0.1

**Foundry Version:**  Core Version: 10.285

**Game System:**  System: dnd5e 2.0.2 (Atropos) 

**Additional context**

![img](https://i.imgur.com/7EL8K7G.png)

Here the journal i'm trying to convert (renamed with txt for github limitation):

[test-journal.json.txt](https://github.com/Meneltamar/fvtt-comprehend-languages/files/9560001/test-journal.json.txt)

**Comment by Meneltamar** [comment]
Just pushed a new release (1.1) where translation of your Journal worked.

**Comment by Meneltamar** [comment]
Just pushed a new release (1.1.1) that skips image pages and seems to work with your journal.

**Comment by p4535992** [comment]
Sorry to bother again, i get this exception now

![img](https://i.imgur.com/pb6nttC.png)

with the same journal

**Comment by Meneltamar** [comment]
Weird, I can't reproduce your bug. I tried it in the pf2e system and 5e, on 10.284 and on 10.285.

How are you hosting/connecting to the game? Do you use the electron app? That would be the only difference, I can think of off the top of my head.

**Comment by ScallDePell** [comment]
Hi Melentamar, same issue for me :
![image](https://user-images.githubusercontent.com/113771783/190853713-1afffe9f-8a79-4c3e-9db7-8d66df757cf2.png)
Version 10 - Build 285
dnd5e 2.0.2
DeepL account and API Key OK
Tested without others modules

Thanks in advance, your module sounds amazing!!!

**Comment by Meneltamar** [comment]
How do you host/connect to the server? Via Chrome/Firefox or are you using
the Electron app?
It's weird that I can't reproduce the issue, but I also haven't tried it in
the Electron app yet.

ScallDePell ***@***.***> schrieb am Sa., 17. Sept. 2022,
13:18:

**Comment by ScallDePell** [comment]
Self hosted
Direct from foundry app ou chrome browser.
I can give you accès on my server if you whant.

**Comment by Meneltamar** [comment]
I can reproduce the issue in Chrome (I was using Firefox so far and there it works without issue).

I'll see what I can do to fix it for Chrome as this seems like a very low-level issue that is not directly correlated with my implementation. But I'll investigate!

**Comment by Meneltamar** [comment]
@ScallDePell @p4535992 
I seem to have been able to fix the issue in the 1.2 release. At least in Chrome it now works on my end. Can't vouch for the Electron app at the moment, but my hope would be that this also fixes it for the app. Please let me know, if you still encounter this issue!

**Comment by ScallDePell** [comment]
Hi Meneltamar,
For me is the same in chrome or app : 
![image](https://user-images.githubusercontent.com/113771783/190895189-3fcd2eda-2763-413d-bd8c-21da1ceaaa85.png)
I have tried with firefox and i have some cross platform errors.

**Comment by Braintelligence** [comment]
I have the same issue with Chrome in Foundry v9. Will you create an update for v9 as well?

**Comment by Meneltamar** [comment]
If I ever manage to find the underlying issue, I could update v9 as well. Unfortunately, I still haven't been able to figure out what is happening here because it works without any issues for me.

**Comment by Meneltamar** [comment]
If you have more details, that would be helpful.
However, I think I have honed in on the Chrome issue in v9:

For some odd reason, Chrome (in v9) doesn't deal well with paragraphs in the text. As soon as the text has a paragraph-break in it, the fetch fails with a TypeError. This does not happen (for me) in Firefox on v9, which is weird, because there should be no difference in how this works.

**Comment by Meneltamar** [comment]
I think, I have a fix. I'll implement it after work (so probably in around 3-4 hours).

**Comment by Meneltamar** [comment]
@Braintelligence @p4535992 : I pushed new releases for Foundry V9 (Version 0.5) and Foundry V10 (Version 1.3). Again, in my local testing on Firefox and Chrome everything worked, but now it definitely seems more "stable" as the paragraph issue in v9 is fixed and I suppose that the root cause for all these issues should be fixed as well.

Please let me know if it still doesn't work.

**Comment by Braintelligence** [comment]
I still get this error in Chrome:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
[Detected 1 package: comprehend-languages]
    at e.buttonTranslateJournalEntry (main.js:1:1365)
```

and this one in Firefox:

```
Uncaught (in promise) TypeError: e is undefined
[Detected 1 package: comprehend-languages]
    buttonTranslateJournalEntry https://my.domain.tld/modules/comprehend-languages/scripts/main.js:1
```

**Comment by Meneltamar** [comment]
@Braintelligence Wait, you are on v9 right? There should be no "map" in the v9 version. Could you check that you are on v0.5?

This is the manifest link (for manual installation, should the autoinstall/-update push you to v1.3):
https://github.com/Meneltamar/fvtt-comprehend-languages/releases/download/v0.5/module.json

**Comment by p4535992** [comment]
This is working for me now (sorry for the long delay). There is still another issue, but i will open another ticket.
